import { format } from 'date-fns'

/**
 * CSV and JSON export utilities
 */

/**
 * Generate CSV content from transactions
 * @param {Transaction[]} transactions
 * @param {Statement[]} statements - for bank/account info
 * @returns {string} CSV string
 */
export function generateCSV(transactions, statements = []) {
  const headers = ['Date', 'Description', 'Amount', 'Type', 'Category', 'Bank', 'Account', 'Balance', 'Month']

  const rows = transactions.map(txn => {
    const stmt = statements.find(s => s.bank === txn.bank)
    return [
      format(txn.date, 'dd/MM/yyyy'),
      `"${(txn.description || '').replace(/"/g, '""')}"`,
      txn.amount.toFixed(2),
      txn.type === 'debit' ? 'Debit' : 'Credit',
      `"${txn.category || 'others'}"`,
      txn.bank?.toUpperCase() || '',
      stmt?.accountNumber || txn.accountNumber || '',
      txn.balance != null ? txn.balance.toFixed(2) : '',
      format(txn.date, 'MMM yyyy'),
    ]
  })

  const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n')
  return csvContent
}

/**
 * Generate a filename for the CSV export
 */
export function generateCSVFilename(statements) {
  if (!statements || statements.length === 0) return 'SpendWise_Export.csv'

  const banks = [...new Set(statements.map(s => s.bankLabel?.split(' ')[0] || s.bank?.toUpperCase()))].join('-')

  // Get date range
  const allMonths = statements.flatMap(s => s.months || [])
  const uniqueMonths = [...new Set(allMonths)].sort()

  const dateRange = uniqueMonths.length > 1
    ? `${uniqueMonths[0].replace(' ', '')}-${uniqueMonths[uniqueMonths.length - 1].replace(' ', '')}`
    : uniqueMonths[0]?.replace(' ', '') || 'Export'

  return `SpendWise_${banks}_${dateRange}.csv`
}

/**
 * Trigger browser download of a CSV file
 */
export function downloadCSV(transactions, statements = []) {
  const csv = generateCSV(transactions, statements)
  const filename = generateCSVFilename(statements)
  downloadFile(csv, filename, 'text/csv;charset=utf-8;')
}

/**
 * Export analytics data as JSON
 */
export function downloadJSON(analyticsData, statements = []) {
  const filename = generateCSVFilename(statements).replace('.csv', '.json')
  const json = JSON.stringify(analyticsData, null, 2)
  downloadFile(json, filename, 'application/json')
}

/**
 * Generate plain text summary for clipboard
 */
export function generateTextSummary(analytics, statements = []) {
  const banks = [...new Set(statements.map(s => s.bankLabel))].join(', ')
  const allMonths = statements.flatMap(s => s.months || [])
  const uniqueMonths = [...new Set(allMonths)].sort()
  const period = uniqueMonths.length > 1
    ? `${uniqueMonths[0]} – ${uniqueMonths[uniqueMonths.length - 1]}`
    : uniqueMonths[0] || 'All time'

  const lines = [
    `SpendWise Summary — ${period}`,
    `Banks: ${banks}`,
    ``,
    `💰 Income:    ${analytics.income}`,
    `💸 Expenses:  ${analytics.expenses}`,
    `💾 Saved:     ${analytics.savings} (${analytics.savingsRate}%)`,
    ``,
    `Top categories:`,
  ]

  if (analytics.categories) {
    analytics.categories.slice(0, 5).forEach((cat, i) => {
      lines.push(`${i + 1}. ${cat.label} ${cat.formatted} (${Math.round(cat.percentage)}%)`)
    })
  }

  lines.push('')
  lines.push('Generated by SpendWise — your finances, clearly.')

  return lines.join('\n')
}

/**
 * Export dashboard as PDF using the browser's native print dialog.
 * Injects a summary header into the DOM, triggers window.print(), then cleans up.
 * @param {Object} opts
 */
export function exportPDF(opts = {}) {
  const {
    income = '',
    expenses = '',
    savings = '',
    savingsRate = '',
    banks = [],
    period = '',
  } = opts

  // Remove any existing print header
  const existing = document.getElementById('spendwise-print-header')
  if (existing) existing.remove()

  const header = document.createElement('div')
  header.id = 'spendwise-print-header'
  header.className = 'print-header'
  // Hidden in screen mode; @media print will show it
  header.style.cssText = 'display:none;'
  header.innerHTML = `
    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:12pt;">
      <div>
        <div style="font-size:18pt;font-weight:700;color:#355CDE;letter-spacing:-0.5pt;">SpendWise</div>
        <div style="font-size:9pt;color:#6B6864;margin-top:2pt;">Finance Report · ${period}</div>
      </div>
      <div style="font-size:9pt;color:#A8A49F;text-align:right;">
        ${banks.join(', ')}<br/>
        <span style="font-size:8pt;">Generated ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</span>
      </div>
    </div>
    <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10pt;">
      <div style="background:#F0FDF4;border-radius:8pt;padding:8pt 10pt;">
        <div style="font-size:8pt;color:#6B6864;margin-bottom:4pt;">Total Income</div>
        <div style="font-size:13pt;font-weight:700;color:#16A34A;">${income}</div>
      </div>
      <div style="background:#FEF2F2;border-radius:8pt;padding:8pt 10pt;">
        <div style="font-size:8pt;color:#6B6864;margin-bottom:4pt;">Total Expenses</div>
        <div style="font-size:13pt;font-weight:700;color:#DC2626;">${expenses}</div>
      </div>
      <div style="background:#EEF2FF;border-radius:8pt;padding:8pt 10pt;">
        <div style="font-size:8pt;color:#6B6864;margin-bottom:4pt;">Net Savings</div>
        <div style="font-size:13pt;font-weight:700;color:#355CDE;">${savings}</div>
      </div>
      <div style="background:#F7F5F1;border-radius:8pt;padding:8pt 10pt;">
        <div style="font-size:8pt;color:#6B6864;margin-bottom:4pt;">Savings Rate</div>
        <div style="font-size:13pt;font-weight:700;color:#111110;">${savingsRate}%</div>
      </div>
    </div>
  `
  document.body.prepend(header)

  // Brief delay so DOM settles before dialog opens
  setTimeout(() => {
    window.print()
    setTimeout(() => header.remove(), 2000)
  }, 120)
}

/**
 * Helper: trigger browser file download
 */
function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
